// This file is auto-generated by openapi-typescript.
// Run `npm run generate-api` to regenerate.
//
// Placeholder — replace once the backend OpenAPI spec is available.
export interface paths {}
export interface components {}
export interface operations {}
